name: 'Setup Docker Build Cache'
description: 'Configure Docker BuildKit cache with intelligent key management'
inputs:
  cache-key:
    description: 'Cache key (typically includes Dockerfile and go.sum hashes)'
    required: true
  cache-paths:
    description: 'Paths to cache'
    required: false
    default: '/tmp/.buildx-cache'
outputs:
  cache-hit:
    description: 'Whether cache was restored'
    value: ${{ steps.cache-restore.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Set up cache directory
      shell: bash
      run: mkdir -p /tmp/.buildx-cache

    - name: Restore Docker build cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.cache-paths }}
        key: ${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set cache output
      shell: bash
      run: |
        if [ "${{ steps.cache-restore.outputs.cache-hit }}" == "true" ]; then
          echo "Docker build cache restored successfully"
        else
          echo "No cache found, will build from scratch"
        fi
